### PR TITLE
Refactor GitLab integration

### PR DESCRIPTION
**Pull request by Ndpnt**
Thanks @fabianospinelli  to the work done in #168 to support GitLab.

This PR refactors the initial implementation to reduce the code duplication.

### CODE REVIEW

**Comment by Ndpnt** [comment]
@alessandrozago Could you please review and confirm that this works as expected? Your validation would be greatly appreciated!

**Comment by Ndpnt** [comment]
Hi @alessandrozago, just following up on my earlier message. Have you had a chance to review it?

**Comment by alessandrozago** [comment]
Hi @Ndpnt , we were able to test the tool for GitLab, and we found just one issue for the "Edit a document declaration" functionality. The functions getProjectId and getModifiedFilesInCommit in the GitLab module do not provide an authentication token in the headers. This means that if the "versions" repository is public it works, but if the repository is private it will not be able to retrieve the information needed.
One possible solution would be to provide an additional token for the versions repository in the env file, similar to what has been done on the engine with a separate token for the releases repository.
Please let me know if you need some other information.

**Comment by Ndpnt** [comment]
Hi @alessandrozago and thanks for your tests and insights!
I think the solution you suggest, i.e. to do something similar to what has been done on the engine, seems to be a good solution. Would you be able to suggest a PR to fix this issue?

**Comment by alessandrozago** [comment]
> Hi @alessandrozago and thanks for your tests and insights! I think the solution you suggest, i.e. to do something similar to what has been done on the engine, seems to be a good solution. Would you be able to suggest a PR to fix this issue?

Hi @Ndpnt . Ok, I will proceed in creating the Pull Request with this fix. Please let me know if I should also open an issue, or if this discussion is enough.

**Comment by Ndpnt** [comment]
> > Hi @alessandrozago and thanks for your tests and insights! I think the solution you suggest, i.e. to do something similar to what has been done on the engine, seems to be a good solution. Would you be able to suggest a PR to fix this issue?
> 
> Hi @Ndpnt . Ok, I will proceed in creating the Pull Request with this fix. Please let me know if I should also open an issue, or if this discussion is enough.

Hi @alessandrozago, this discussion is enough. Thanks for asking.

**Pull request merged**
