### PR TITLE
List instances 

### PR DESCRIPTION
**Pull request by martinratinaud**
Give a way to select an existing instance instead of relying on a query param.

### CODE REVIEW

**Comment by martinratinaud** [comment]
> Please do not add a way to select instances from the GUI. This will enable uncontrolled contribution and we don't have the resources to handle that.

I remembered this was an initial demand from @clementbiron 


I also believe the likelyhood of somebody contributing directly by ending up on htttps://contribute.opentermsarchive.org is very small.
The documentation on this query param is also documented so anybody really willing to do would be able to.

The benefits I see on the other side is that I, as a maintainer of several instances, often go to the contribution tool and having a select box is a good addition so that I don't make a mistake

Anyway, I will comment out the code on this until we can discuss about that.

**Review by MattiSG — CHANGES_REQUESTED** [review]
> I, as a maintainer of several instances […]

I understand that. However there are at most 4 people in that situation, all core team members, who can be trained 🙂 On the other hand, adding this power to an already very powerful tool is too likely to lead to uncontrolled contribution.

If you truly want this feature for yourself, can you please hide it behind a feature flag? Thank you 🙂

**Comment by martinratinaud** [comment]
@clementbiron What do you think then?

1. do not implement
2. implement behind query param `?instances`
3.  implement behind query param `?something-else`

**Comment by martinratinaud** [comment]
Let's close it then as it does not seem to be really needed for now

**Pull request closed without merging**
